name: BC check

on:
  pull_request:
  workflow_dispatch:

jobs:
  bc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: '1'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Install dependencies
        run: composer require --dev roave/backward-compatibility-check:^8.13

      - name: Run bc-check
        run: composer bc-check -- --format=github-actions --from="origin/${{ github.base_ref }}"
